Removed support for MozReview
mozilla/code-coverage-addon pull request #48
Opened 2018-10-03 18:30 UTC by arshadkazmi42

MozReview support removed.

- Deleted `mozreview` file
- Removed all references to mozreivew

Closes #47

2018-10-03 23:16 UTC, marco-c requested changes
Thanks! The patch looks good overall, I think you got almost all the instances of MozReview.
The only missing one is the actual MozReview website, I forgot to mention it: reviewboard-hg.mozilla.org. All references to this website should be removed too.

Don't worry about the linting failures, they are preexisting.

2018-10-04 02:43 UTC, arshadkazmi42 commented
@marco-c Thank you for the review. I have completed the requested changes.

2018-10-04 08:24 UTC, marco-c commented on manifest.json
>      {
This entry should be removed too, we don't want to inject scripts into reviewboard.mozilla.org anymore

2018-10-04 08:46 UTC, arshadkazmi42 commented on manifest.json
>      {
@marco-c whole object from line 29 - 34?

2018-10-04 08:54 UTC, marco-c commented on manifest.json
>      {
Yes, the object referring to mozreview

2018-10-04 09:00 UTC, marco-c approved these changes
Thanks! Everything should have been caught now!

2018-10-04 09:00 UTC, arshadkazmi42 commented on manifest.json
>      {
done with that change

2018-10-04 09:01 UTC, merged

2018-10-04 09:03 UTC, arshadkazmi42 commented
@marco-c Thank you